robots:
  - name: robot1
    x: 0.5
    y: 2.0
    z: 0.01
    Y: 0.0
  - name: robot2
    x: 8.5
    y: 8.5
    z: 0.01
    Y: 3.14
  - name: robot3
    x: 0.6
    y: 8.0
    z: 0.01
    Y: 0.0
  - name: robot4
    x: 3.5
    y: 3.35
    z: 0.01
    Y: 3.14

target:
  - name: charging_1
    x: 0.9
    y: 5.95
    z: 0.01
  - name: charging_2
    x: 7.0
    y: 0.8
    z: 0.01
  - name: vending_1
    x: 1.5
    y: 1.25
    z: 0.01
  - name: service_1
    x: 5.2
    y: 8.7
    z: 0.01

OBSERVE_STEPS:  

ACTION_SIZE: 2
HIDDEN_SIZE: 512
BATCH_SIZE: 1024
BUFFER_SIZE: 1000000
DISCOUNT_FACTOR: 0.99
LEARNING_RATE: 0.0003
TAU: 0.0003
STEP_TIME: 0.01
EPSILON_DECAY: 0.9995
EPSILON_MINIMUM: 0.05

POLICY_NOISE: 0.2
POLICY_NOISE_CLIP: 0.5
POLICY_UPDATE_FREQUENCY: 2

LINEAR: 0
ANGULAR: 1

SPEED_LINEAR_MAX: 0.22
SPEED_ANGULAR_MAX: 2.0

LIDAR_DISTANCE_CAP: 3.5
NUM_SCAN_SAMPLES: 360

THRESHOLD_COLLISION: 0.16
THRESHOLD_GOAL: 0.6
OBSTACLE_RADIUS: 0.16
MAX_NUMBER_OBSTACLES: 3

UNKNOWN: 0
SUCCESS: 1
COLLISION_WALL: 2
COLLISION_OBSTACLE: 3
TIMEOUT: 4
TUMBLE: 5

EPISODE_TIMEOUT_SECONDS: 100
MAX_EPISODE_DURATION: 300
